### ISSUE TITLE
📣 Next V4 release

### ISSUE THREAD

**Issue by wa0x6e** [wa0x6e/cal-heatmap#278]
Hello world,

Next version of CalHeatmap (V4) is in progress, and will be a major update from current state.
After 6 years of inactivity, the code is pretty out-of-date with current technology, and I decided to proceed to a full refactoring of the code base, since javascript and browser support has evolved since.

### New/Planned features and fixes

Current tickets and PR will be closed as the concerns raised in the tickets are implemented in the v4 branch

- [x] Update D3js to v7
- [x] Fix #249 
- [x] Fix #163 
- [x] Fix #82 
- [x] Fix #169 
- [x] Fix #171 
- [x] Fix #265 
- [x] Fix #91  
- [x] Fix #186 
- [x] Fix #257  
- [x] Fix #115  
- [x] Fix #95  
- [x] Fix #154  
- [x] Fix #189  
- [x] Fix #131 
- [x] Fix #87 
- [x] Fix #52 
- [x] Fix #164
- [x] Fix #238 
- [x] Fix #134
- [x] Fix #158
- [x] Fix #260
- [x] Fix #90 
- [x] Fix #127
- [x] Fix #266
- [x] Fix #216
- [x] Fix #176
- [x] Fix #241
- [x] Fix #111
- [x] Fix #100
- [x] Add output for ESM
- [x] Add output for UMD
- [x] All times handling have been delegated to moment-timezone, should be fixed, have to test
- [x] Localize date(currently only using browser language)
- [x] New customization option, so domain and subDomain can be customized via a template, on init(). Users will be able to customize the layout, such as displaying only weekdays, only last 365 days, etc ...
- [x] Moment-timezone seems to not take locale into account (https://github.com/moment/moment-timezone/issues/647#issuecomment-439600573)
- [x] Implement this legend layout: https://observablehq.com/@d3/color-legend
- [x] All events are renamed, and is handled by an event emitter

### Internal changes

All internal API have changed. If your code is relying on anything other than the public API, it'll surely fail.
Some public API have also changed.

- [x] Code have been upgraded to use new ES6 methods, and will use babel to transpile to old JS
- [x] Code have been split into multiple classes/modules, instead of a single monolithic file 
- [x] Code standard/formatting have been updated, refer to eslint and prettier config
- [x] Build files are now located in a `dist` folder, instead of root 
- [x] Replacing d3-time with momentjs, moment-timezone and moment-range 
- [x] Migrate code to typescript 

### ToDo

- [x] Refactor all test with Jest framework
- [x] Update Changelog
- [x] Update build tools (grunt and rollup), to output correct build files
- [x] Builds with and without momentjs locale data

**Comment by wa0x6e** [comment]
v4 branch has been merged into master.

Code is now more or less functional, with all migration steps completed.
Starting now working on bugfixes and enhancement

**Comment by ChiaYuSu** [comment]
> v4 branch has been merged into master.
> 
> Code is now more or less functional, with all migration steps completed. Starting now working on bugfixes and enhancement

Is there any v4 version cdn.js available now? 
Thank you.

**Comment by wa0x6e** [comment]
Not yet

**Comment by wa0x6e** [comment]
Most of the bug and features ticket have been closed.
Build is now in beta, and seems functional.

Most of the next commits will focus on some refactoring while writting tests.

**Comment by wa0x6e** [comment]
We're now in beta 3

Still pending in the todo are:
- [ ] Basic legend plugin, to bring back the old legend, similar to github contribution graph
- [ ] Looking to replace momentjs by day.js
- [ ] Add more tests on older browsers

Documentation website is being updated along, don't forget to take a look at the example: https://cal-heatmap.com/examples.html

**Comment by Loksly** [comment]
Looks awesome, thanks for this improvement.

**Comment by scarroll32** [comment]
Thank you!

**Comment by wa0x6e** [comment]
New documentation website is live

**Comment by wa0x6e** [comment]
We're reaching a pretty stable, and production ready build after 11 betas.

Last point on the roadmap would be to reintroduce the old basic legend, via a plugin
